version: '3'

services:
  mysql:
    container_name: mysql_container
    image: mysql:8.0
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: potzdb
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./volumes/db_data:/var/lib/mysql
