### signup
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
  "email": "hi3@example.com",
  "name": "hihi",
  "password": "1234"
}

### login 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "hi3@example.com",
  "password": "1234"
}

### join community
PATCH http://localhost:5000/communities/2/join


### confirm order
PATCH http://localhost:5000/orders/1/order-confirm
Content-Type: application/json
