-- AlterTable
ALTER TABLE `Message` MODIFY `type` ENUM('SYSTEM', 'TEXT', 'IMAGE', 'REQUEST', 'ORDER', 'ORDER_CONFIRM', 'DEPOSIT', 'DEPOSIT_CONFIRM') NOT NULL DEFAULT 'TEXT';

-- AlterTable
ALTER TABLE `UserProfile` ADD COLUMN `accountHolderName` VARCHAR(191) NULL,
    ADD COLUMN `bankName` VARCHAR(191) NULL;
